name: Deploy

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'mothership.ravern.dev'
            app-name: 'cooking'
            git-push-flags: '--force'

